# Generated by Django 4.2.5 on 2023-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_create',
            field=models.TextField(default='None'),
        ),
    ]
