# Generated by Django 4.2.5 on 2023-10-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_date_create_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
