# Generated by Django 4.2.5 on 2023-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(),
        ),
    ]
