# Generated by Django 4.2.5 on 2023-10-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_status_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
    ]
